
# This is an example. Copy to my.config.yml in this directory
dev:
  domain: https://playexquisitecorpse-dev.com
  certificate: arn:aws:acm:us-west-1:account-id:certificate/abc-123
  throttleRateLimit: 200
  throttleBurstLimit: 100

prod:
  domain: https://playexquisitecorpse.com
  certificate: arn:aws:acm:us-west-1:account-id:certificate/abc-1234
  throttleRateLimit: 2000
  throttleBurstLimit: 1000

